from pathlib import Path
import re

path = Path('admin-stocktake.html')
s = path.read_text()

css_marker = '<style id="v56-7-readable-audit">'
if css_marker not in s:
    css = r'''
<style id="v56-7-readable-audit">
.auditFields{display:grid;gap:5px;min-width:0}.auditField{display:flex;align-items:flex-start;gap:6px;min-width:0;line-height:1.5}.auditFieldLabel{flex:0 0 auto;color:var(--s);font-weight:600}.auditFieldValue{min-width:0;overflow-wrap:anywhere;word-break:normal;color:var(--p)}.auditEmpty{color:var(--m)}.auditCell{min-width:180px;max-width:330px;white-space:normal!important;vertical-align:top}.auditContext{margin-top:5px;padding-top:5px;border-top:1px dashed var(--b)}.auditBox{border:1px solid var(--b);border-radius:11px;background:var(--sf);padding:9px;min-width:0}.auditBoxTitle{font-size:11px;font-weight:700;color:var(--s);margin-bottom:5px}.auditChangeGrid{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px}.auditCardTitle{font-size:15px;font-weight:700}.auditCardMeta{font-size:12px;color:var(--s);line-height:1.55;margin-top:2px}
@media(max-width:719px){.auditChangeGrid{grid-template-columns:1fr}.auditField{font-size:13px}.auditBoxTitle{font-size:12px}.auditCell{min-width:0;max-width:none}}
</style>
'''
    s = s.replace('</head>', css + '</head>', 1)

replacement = r'''function auditActionLabels(){return {count_created:'اعتماد العد الأول',count_revised:'تعديل الجرد',quantity_found_later:'كمية عُثر عليها لاحقًا',note_updated:'تعديل الملاحظة',team_created:'إنشاء مجموعة',team_updated:'تعديل المجموعة',team_deleted:'حذف مجموعة',team_items_imported:'اعتماد ملف مجموعة قديم',campaign_created:'إنشاء الجرد',test_campaign_created:'إنشاء تجربة جرد',campaign_ready:'اعتماد التجهيز',campaign_activated:'بدء الجرد',campaign_closed:'إغلاق الجرد',campaign_reopened:'إعادة فتح الجرد'}}
function auditFieldLabels(){return {sku:'رقم الصنف',name:'اسم المجموعة',scope:'نطاق الجرد',zone:'نطاق الجرد',warehouse:'المستودع',stocktakeDate:'تاريخ الجرد',actualQty:'الكمية الفعلية',expectedQty:'كمية النظام',difference:'الفرق',countStatus:'الحالة',note:'الملاحظة',revision:'عدد التعديلات',memberEmployeeNames:'أعضاء اللجنة',extraMemberNames:'المساعدون',itemCount:'عدد الأصناف',count:'عدد الأصناف',pending:'أصناف متبقية',fileName:'اسم الملف',replaced:'أصناف سابقة',removed:'أصناف محذوفة',status:'الحالة',quantity:'الكمية',foundQty:'الكمية التي عُثر عليها',delta:'الكمية المضافة',oldQty:'الكمية السابقة',newQty:'الكمية الجديدة',reason:'السبب',testSource:'مصدر التجربة',sourceMode:'مصدر الجرد'}}
function auditParts(x){const d=x&&x.data&&typeof x.data==='object'?x.data:{};return {before:x?.before??d.before??null,after:x?.after??d.after??null,context:d}}
function auditValue(k,v){if(v===null||v===undefined||v==='')return '—';if(k==='countStatus')return itemStatus(v);if(k==='difference'){const n=Number(v);return Number.isFinite(n)?`${n>0?'+':''}${fmt(n)}`:String(v)}if(['actualQty','expectedQty','quantity','foundQty','delta','oldQty','newQty','itemCount','count','pending','replaced','removed','revision'].includes(k)){const n=Number(v);return Number.isFinite(n)?fmt(n):String(v)}if(k==='testSource'||k==='sourceMode')return String(v)==='current_inventory'?'المخزون الحالي':String(v)==='excel'?'ملف Excel':String(v);if(Array.isArray(v))return v.length?v.map(x=>String(x)).join('، '):'—';if(typeof v==='boolean')return v?'نعم':'لا';return String(v)}
function auditEntries(obj){if(!obj||typeof obj!=='object'||Array.isArray(obj))return [];const labels=auditFieldLabels(),hidden=new Set(['campaignId','teamId','memberEmployeeIds','actorEmployeeId','normalizedSku','schemaVersion','userAgent','createdAt','updatedAt','before','after','id']);const seen=new Set();return Object.entries(obj).filter(([k,v])=>labels[k]&&!hidden.has(k)&&v!==undefined&&v!==null&&v!==''&&!(Array.isArray(v)&&!v.length)).filter(([k])=>{const semantic=k==='zone'?'scope':k;if(seen.has(semantic))return false;seen.add(semantic);return true}).map(([k,v])=>({label:labels[k],value:auditValue(k,v)}))}
function auditSnapshotHtml(obj,emptyText='لا توجد بيانات'){if(obj===null||obj===undefined)return `<span class="auditEmpty">${esc(emptyText)}</span>`;if(typeof obj!=='object'||Array.isArray(obj))return `<div class="auditFields"><div class="auditField"><span class="auditFieldValue">${esc(auditValue('',obj))}</span></div></div>`;const rows=auditEntries(obj);return rows.length?`<div class="auditFields">${rows.map(r=>`<div class="auditField"><span class="auditFieldLabel">${esc(r.label)}:</span><span class="auditFieldValue">${esc(r.value)}</span></div>`).join('')}</div>`:`<span class="auditEmpty">${esc(emptyText)}</span>`}
function auditContextHtml(x){const {context}=auditParts(x),rows=auditEntries(context);if(!rows.length)return '';return `<div class="auditContext"><div class="auditFields">${rows.map(r=>`<div class="auditField"><span class="auditFieldLabel">${esc(r.label)}:</span><span class="auditFieldValue">${esc(r.value)}</span></div>`).join('')}</div></div>`}
function auditHtml(){const a=state.audit.slice(0,250),labels=auditActionLabels();return `<div class="tablewrap"><table class="table"><thead><tr><th>الوقت</th><th>الصنف</th><th>الحركة</th><th>بواسطة</th><th>قبل</th><th>بعد</th><th>التفاصيل</th></tr></thead><tbody>${a.length?a.map(x=>{const p=auditParts(x);return `<tr><td>${dt(x.createdAt)}</td><td>${esc(x.sku||p.context?.sku||'—')}</td><td><b>${esc(labels[x.action]||x.action||'حركة')}</b></td><td>${esc(x.actorName||'—')}</td><td class="auditCell">${auditSnapshotHtml(p.before,'لا توجد حالة سابقة')}</td><td class="auditCell">${auditSnapshotHtml(p.after,'لا توجد حالة جديدة')}</td><td class="auditCell">${auditContextHtml(x)||'<span class="auditEmpty">—</span>'}</td></tr>`}).join(''):'<tr><td colspan="7" class="empty">لا توجد تعديلات بعد.</td></tr>'}</tbody></table></div>`}
function auditCardsHtml(){const a=state.audit.slice(0,250),labels=auditActionLabels();return `<div class="mobileAudit">${a.length?a.map(x=>{const p=auditParts(x),sku=x.sku||p.context?.sku||'';return `<article class="mobileItem"><div class="mobileItemHead"><div class="grow"><div class="auditCardTitle">${esc(labels[x.action]||x.action||'حركة')}</div><div class="auditCardMeta">${dt(x.createdAt)} · ${esc(x.actorName||'—')}</div></div>${sku?`<span class="pill">${esc(sku)}</span>`:''}</div><div class="auditChangeGrid"><div class="auditBox"><div class="auditBoxTitle">قبل</div>${auditSnapshotHtml(p.before,'لا توجد حالة سابقة')}</div><div class="auditBox"><div class="auditBoxTitle">بعد</div>${auditSnapshotHtml(p.after,'لا توجد حالة جديدة')}</div></div>${auditContextHtml(x)}</article>`}).join(''):'<div class="empty">لا توجد تعديلات بعد.</div>'}</div>`}
function printHtml(cp){'''

pattern = r"function auditHtml\(\)\{.*?\nfunction printHtml\(cp\)\{"
s2, n = re.subn(pattern, replacement, s, count=1, flags=re.S)
if n != 1:
    raise SystemExit(f'Expected one audit block replacement, got {n}')

path.write_text(s2)
print('V56.7 readable audit patch applied')
