from pathlib import Path
p=Path('customer.html')
s=p.read_text()
marker="    // V42_FINISH: post-checkout consistency for passwordless customers.\n"
if marker not in s:
    raise SystemExit('V42_SECURE_INSERT_MARKER')
if 'V42_SECURE: invisible Firebase session' not in s:
    block=r'''    // V42_SECURE: invisible Firebase session keeps Firestore writes authenticated without asking the customer for credentials.
    html=html.replace("if(creatingAccountRef.current) return;","if(creatingAccountRef.current||(()=>{try{return localStorage.getItem('batco_quick_customer_creating_v1')==='1'}catch{return false}})()) return;");
    const secureQuick42=[
      "  async function ensureQuickCustomer(company){",
      "    const cleanCompany=String(company||quickProfile?.company||'').trim().replace(/\\s+/g,' '),cleanName=String(guestName||currentGuestName()||'').trim().replace(/\\s+/g,' ');if(cleanName.length<2)throw new Error('NAME_REQUIRED');if(cleanCompany.length<2)throw new Error('COMPANY_REQUIRED');",
      "    const previous=currentQuickCustomerProfile();let accountUser=auth.currentUser,createdNow=false;try{if(!accountUser){try{localStorage.setItem('batco_quick_customer_creating_v1','1')}catch{}const safeVisitor=String(customerVisitorId||'customer').replace(/[^a-zA-Z0-9]/g,'').slice(-32),email=`quick_${safeVisitor}_${Date.now().toString(36)}_${uidPart()}@customer.batco.local`,bytes=crypto.getRandomValues(new Uint8Array(24)),password='Q9!'+Array.from(bytes,b=>b.toString(36)).join('').slice(0,42);const cred=await auth.createUserWithEmailAndPassword(email,password);accountUser=cred.user;createdNow=true}const uid=accountUser.uid,next={uid,id:uid,visitorId:customerVisitorId,name:cleanName,company:cleanCompany,phone:'',branches:[...branches],status:'active',accountType:'passwordless_device',authMode:'firebase_persisted_session',passwordless:true};const payload={visitorId:customerVisitorId,name:cleanName,company:cleanCompany,phone:'',branches:next.branches,status:'active',accountType:'passwordless_device',authMode:'firebase_persisted_session',passwordless:true,lastSeenAt:firebase.firestore.FieldValue.serverTimestamp(),lastActivityAt:firebase.firestore.FieldValue.serverTimestamp(),lastActivityType:'quick_account_ready',schemaVersion:7,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};if(!previous?.uid)payload.createdAt=firebase.firestore.FieldValue.serverTimestamp();await db.collection(CUSTOMER_COLLECTION).doc(uid).set(payload,{merge:true});await ensureCustomerDeviceAllowed(accountUser,next);persistQuickCustomerProfile(next);setQuickProfile(next);try{localStorage.removeItem('batco_quick_customer_creating_v1')}catch{}await Promise.allSettled([touchCustomerSession(accountUser,next,'quick_account_ready'),logCustomerEvent(accountUser,'quick_account_ready',cleanCompany,{company:cleanCompany})]);return next}catch(error){try{localStorage.removeItem('batco_quick_customer_creating_v1')}catch{}if(createdNow&&accountUser&&!previous?.uid){try{await accountUser.delete()}catch{}}throw error}",
      "  }",""
    ].join('\n');
    html=replaceBetween(html,"  async function ensureQuickCustomer(company){","  async function saveDraft(notes='')",secureQuick42,'V42_SECURE_ACCOUNT');
    const secureSubmit42=[
      "  async function submitOrder(notes='',company=''){",
      "    const cleanNotes=String(notes||'').trim();if(!cartItems.length){setToast({type:'error',message:'السلة فارغة.'});return}if(EMPLOYEE_CUSTOMER_VIEW){setToast({type:'info',message:employeeViewNotice});return}setSubmitBusy(true);setValidationErrors([]);",
      "    try{const allowed=await freshAllowedMap(),errors=cartItems.map(i=>({cleanId:i.cleanId,id:i.id,requested:i.totalQty,allowed:allowed.get(i.cleanId)||0})).filter(x=>x.requested>x.allowed+1e-9);if(errors.length){setValidationErrors(errors);setToast({type:'error',message:'تغير المتاح لبعض الأصناف. عدّل الكمية ثم أعد الاعتماد.'});return}let orderProfile=safeProfile,orderUid=String(user?.uid||''),orderUser=user;if(guestMode){orderProfile=await ensureQuickCustomer(company);orderUid=orderProfile.uid;orderUser=auth.currentUser}const ref=db.collection(ORDER_COLLECTION).doc(),orderNo='BT-'+ref.id.slice(0,7).toUpperCase(),orderItems=cartItems.map(i=>({cleanId:i.cleanId,id:i.id,name:i.name,cartonPrice:Number(i.cartonPrice)||0,pack:i.pack||'',branchQuantities:i.branchQuantities,totalQty:i.totalQty})),orderCore={customerUid:orderUid,orderNo,customer:{name:orderProfile.name||currentGuestName(),company:orderProfile.company||String(company||'').trim(),phone:''},branches:branches.map(b=>({id:b.id,name:b.name})),items:orderItems,notes:cleanNotes,totalCartons,estimatedTotal:sum(cartItems.map(i=>(Number(i.cartonPrice)||0)*Number(i.totalQty||0))),status:'submitted',accountType:guestMode?'passwordless_device':'legacy_account'};await ref.set({...orderCore,createdAt:firebase.firestore.FieldValue.serverTimestamp(),checkoutVersion:7});const receipt={id:ref.id,...orderCore,createdAtLocal:Date.now()};try{sessionStorage.setItem(LAST_SUBMITTED_ORDER_KEY,JSON.stringify(receipt))}catch{}setSubmittedOrder(receipt);clearCustomerPendingAction();setCart({});setCheckout(false);await Promise.allSettled([db.collection(CUSTOMER_COLLECTION).doc(orderUid).set({lastOrderNo:orderNo,lastOrderId:ref.id,lastOrderAt:firebase.firestore.FieldValue.serverTimestamp(),orderCount:firebase.firestore.FieldValue.increment(1),lastActivityAt:firebase.firestore.FieldValue.serverTimestamp(),lastActivityType:'order_submitted'},{merge:true}),logCustomerEvent(orderUser,'order_submitted',orderNo,{orderId:ref.id,itemCount:cartItems.length,totalCartons}),touchCustomerSession(orderUser,orderProfile,'order_submitted')]);",
      "    }catch(e){console.error(e);setToast({type:'error',message:e?.message==='COMPANY_REQUIRED'?'اكتب اسم الشركة أو المؤسسة للمتابعة.':'تعذر اعتماد الطلب. السلة لم تُحذف؛ تحقق من الاتصال وحاول مرة أخرى.'})}finally{setSubmitBusy(false)}",
      "  }",""
    ].join('\n');
    html=replaceBetween(html,"  async function submitOrder(notes='',company=''){","  async function shareOrderWhatsApp(order){",secureSubmit42,'V42_SECURE_SUBMIT');
    html=html.replace("const nav=guestMode?[['home','home','الرئيسية'],['categories','grid','الأقسام'],['cart','cart','السلة']]:[['home','home','الرئيسية'],['categories','grid','الأقسام'],['cart','cart','السلة'],['orders','file','طلباتي']];","const nav=guestMode?[['home','home','الرئيسية'],['categories','grid','الأقسام'],['cart','cart','السلة']]:(safeProfile.passwordless?[['home','home','الرئيسية'],['categories','grid','الأقسام'],['cart','cart','السلة'],['orders','file','طلباتي']]:[['home','home','الرئيسية'],['categories','grid','الأقسام'],['cart','cart','السلة'],['orders','file','طلباتي'],['account','user','حسابي']]);");
    if(!html.includes("authMode:'firebase_persisted_session'")||!html.includes('createUserWithEmailAndPassword(email,password)')||!html.includes("checkoutVersion:7")||!html.includes('safeProfile.passwordless?'))throw new Error('V42_SECURE_OUTPUT_CHECK');
'''
    s=s.replace(marker,block+marker,1)
p.write_text(s)
print('V42_SECURE_PATCHED')
