from pathlib import Path
p=Path('customer.html')
s=p.read_text()
helper_marker="  const CORE='./runtime/customer-v37-source.txt?v=37.1';\n"
helper="  const replaceBetween=(src,start,end,replacement,label)=>{const a=src.indexOf(start);if(a<0)throw new Error(label+'_START');const b=src.indexOf(end,a+start.length);if(b<0)throw new Error(label+'_END');return src.slice(0,a)+replacement+src.slice(b)};\n"
if helper not in s:
    if helper_marker not in s: raise SystemExit('V42_HELPER')
    s=s.replace(helper_marker,helper_marker+helper,1)
marker="    if(!html.includes(\"EMPLOYEE_CUSTOMER_ROUTE.get('employeeView')==='1'\")||!html.includes(\"EMPLOYEE_CUSTOMER_SESSION.name||'موظف'\")||!html.includes('!EMPLOYEE_CUSTOMER_VIEW&&guestMode&&showGuestNamePrompt')||!html.includes('handoffEmployeeCustomerCart(cartItems,branches)')||!html.includes('EMPLOYEE_CUSTOMER_CART_TRANSFER_BACKUP_KEY')||!html.includes('نقل ومتابعة الاعتماد')||!html.includes('setShowGuestNamePrompt(true),5000')||!html.includes(\"skipped:'guest_name_pending'\")||!html.includes('سجل اسمك للمتابعة'))throw new Error('V41_CUSTOMER_OUTPUT_CHECK');\n"
if marker not in s: raise SystemExit('V42_INSERT')
block=r'''    // V42: no customer password, phone, or face flow. First checkout asks only for company name.
    const id42=[
      "const currentGuestName=()=>{try{return String(localStorage.getItem(GUEST_NAME_KEY)||'').trim()}catch{return''}};",
      "const QUICK_CUSTOMER_PROFILE_KEY='batco_quick_customer_profile_v1';",
      "const currentQuickCustomerProfile=()=>{try{const p=JSON.parse(localStorage.getItem(QUICK_CUSTOMER_PROFILE_KEY)||'null');return p&&p.uid?{...p,name:String(p.name||currentGuestName()).trim(),company:String(p.company||'').trim(),phone:'',branches:Array.isArray(p.branches)?p.branches:[]}:null}catch{return null}};",
      "const quickCustomerUid=()=>`qc_${String(customerVisitorId||'visitor').replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,150)}`;",
      "const persistQuickCustomerProfile=p=>{try{localStorage.setItem(QUICK_CUSTOMER_PROFILE_KEY,JSON.stringify(p))}catch{}return p};",
      "const customerIdentity=user=>{const q=currentQuickCustomerProfile();if(user?.uid)return {key:`u_${user.uid}`,customerUid:user.uid,visitorId:customerVisitorId,identityType:'account'};if(q?.uid)return {key:`u_${q.uid}`,customerUid:q.uid,visitorId:customerVisitorId,identityType:'passwordless_device'};return {key:`g_${customerVisitorId}`,customerUid:'',visitorId:customerVisitorId,identityType:'guest'}};"
    ].join('\n');
    html=replaceBetween(html,"const currentGuestName=()=>","const CUSTOMER_DEVICE_INSTALL_KEY=",id42+'\n','V42_IDENTITY');

    const telemetry42=[
      "async function logCustomerEvent(user,type,label='',data={}){",
      "  if(['127.0.0.1','localhost'].includes(location.hostname))return {activity:false,profile:false,skipped:'local_qa'};if(!user?.uid&&window.__employeeCustomerView)return {activity:false,profile:false,skipped:'employee_view'};if(!user?.uid&&!currentGuestName())return {activity:false,profile:false,skipped:'guest_name_pending'};",
      "  const identity=customerIdentity(user),device=customerDeviceInfo(),guestName=currentGuestName(),writes=[db.collection(CUSTOMER_ACTIVITY_COLLECTION).add({customerUid:identity.customerUid,visitorId:identity.visitorId,identityType:identity.identityType,name:user?.uid?'':guestName,sessionId:customerSessionId,type,label:String(label||''),data:data||{},device,createdAt:firebase.firestore.FieldValue.serverTimestamp()})];",
      "  if(identity.customerUid)writes.push(db.collection(CUSTOMER_COLLECTION).doc(identity.customerUid).set({visitorId:identity.visitorId,lastActivityAt:firebase.firestore.FieldValue.serverTimestamp(),lastActivityType:String(type||'activity'),lastActivityLabel:String(label||''),lastSessionId:customerSessionId,lastSeenAt:firebase.firestore.FieldValue.serverTimestamp(),telemetryVersion:6},{merge:true}));const results=await Promise.allSettled(writes);return {activity:results[0]?.status==='fulfilled',profile:identity.customerUid?(results[1]?.status==='fulfilled'):false};",
      "}",
      "async function touchCustomerSession(user,profile,event='active'){",
      "  if(['127.0.0.1','localhost'].includes(location.hostname))return {skipped:'local_qa'};if(!user?.uid&&window.__employeeCustomerView)return {skipped:'employee_view'};if(!user?.uid&&!currentGuestName())return {skipped:'guest_name_pending'};const identity=customerIdentity(user),device=customerDeviceInfo(),resolved=profile||currentQuickCustomerProfile()||{};",
      "  try{const key='batco_customer_session_started_'+identity.key+'_'+customerSessionId,first=!sessionStorage.getItem(key),payload={customerUid:identity.customerUid,visitorId:identity.visitorId,identityType:identity.identityType,sessionId:customerSessionId,name:String(resolved.name||currentGuestName()).trim(),company:resolved.company||'',phone:'',event,lastActive:firebase.firestore.FieldValue.serverTimestamp(),device,userAgent:device.userAgent||'',platform:device.platform||''};if(first){payload.startedAt=firebase.firestore.FieldValue.serverTimestamp();sessionStorage.setItem(key,'1')}await db.collection(CUSTOMER_SESSION_COLLECTION).doc(`${identity.key}_${customerSessionId}`).set(payload,{merge:true});return {session:true}}catch(e){console.warn('[Customer session]',e?.message||e);return {session:false}}",
      "}",""
    ].join('\n');
    html=replaceBetween(html,"async function logCustomerEvent(user,type,label='',data={}){","function normalizePhone(raw){",telemetry42,'V42_TELEMETRY');

    const appOld="function CustomerApp({user,profile,onProfileUpdate,guestMode=false,onRequireAuth}){\n  const safeProfile=profile||{name:'',company:'',phone:'',branches:[]};\n  const employeeViewNotice=";
    const appNew="function CustomerApp({user,profile,onProfileUpdate,guestMode=false,onRequireAuth}){\n  const [quickProfile,setQuickProfile]=useState(()=>currentQuickCustomerProfile());\n  const safeProfile=profile||quickProfile||{name:currentGuestName(),company:'',phone:'',branches:[]};\n  const employeeViewNotice=";
    if(!html.includes(appOld))throw new Error('V42_APP');html=html.replace(appOld,appNew);
    html=html.replace("const profileNow=()=>({name:currentGuestName(),company:'',phone:''});","const profileNow=()=>currentQuickCustomerProfile()||{name:currentGuestName(),company:'',phone:''};");

    const saveNameOld="  const saveGuestName=async clean=>{\n    try{localStorage.setItem(GUEST_NAME_KEY,clean)}catch{}\n    setGuestName(clean);setShowGuestNamePrompt(false);\n    await Promise.allSettled([\n      touchCustomerSession(null,{name:clean,company:'',phone:''},'guest_name_captured'),\n      logCustomerEvent(null,'guest_name_captured',clean,{name:clean,source:'name_prompt'})\n    ]);\n  };";
    const saveNameNew="  const saveGuestName=async clean=>{try{localStorage.setItem(GUEST_NAME_KEY,clean)}catch{}setGuestName(clean);setShowGuestNamePrompt(false);const old=currentQuickCustomerProfile();if(old?.uid){const next=persistQuickCustomerProfile({...old,name:clean});setQuickProfile(next);db.collection(CUSTOMER_COLLECTION).doc(old.uid).set({name:clean,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true}).catch(()=>{})}await Promise.allSettled([touchCustomerSession(null,currentQuickCustomerProfile()||{name:clean,company:'',phone:''},'guest_name_captured'),logCustomerEvent(null,'guest_name_captured',clean,{name:clean,source:'name_prompt'})])};";
    if(!html.includes(saveNameOld))throw new Error('V42_NAME');html=html.replace(saveNameOld,saveNameNew);

    const account42=[
      "  async function ensureQuickCustomer(company){",
      "    const cleanCompany=String(company||quickProfile?.company||'').trim().replace(/\\s+/g,' '),cleanName=String(guestName||currentGuestName()||'').trim().replace(/\\s+/g,' ');if(cleanName.length<2)throw new Error('NAME_REQUIRED');if(cleanCompany.length<2)throw new Error('COMPANY_REQUIRED');const old=currentQuickCustomerProfile(),uid=old?.uid||quickCustomerUid(),next={uid,id:uid,visitorId:customerVisitorId,name:cleanName,company:cleanCompany,phone:'',branches:[...branches],status:'active',accountType:'passwordless_device',authMode:'device_bound',passwordless:true};",
      "    const payload={visitorId:customerVisitorId,name:cleanName,company:cleanCompany,phone:'',branches:next.branches,status:'active',accountType:'passwordless_device',authMode:'device_bound',passwordless:true,lastSeenAt:firebase.firestore.FieldValue.serverTimestamp(),lastActivityAt:firebase.firestore.FieldValue.serverTimestamp(),lastActivityType:'quick_account_ready',schemaVersion:6,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};if(!old?.uid)payload.createdAt=firebase.firestore.FieldValue.serverTimestamp();await db.collection(CUSTOMER_COLLECTION).doc(uid).set(payload,{merge:true});persistQuickCustomerProfile(next);setQuickProfile(next);return next;",
      "  }",
      "  async function saveDraft(notes=''){if(!cartItems.length)return;if(EMPLOYEE_CUSTOMER_VIEW){setToast({type:'info',message:employeeViewNotice});return}setToast({type:'info',message:'لتبسيط الطلب، اعتمد الطلب مباشرة. سيتم حفظ حسابك تلقائيًا بدون تسجيل دخول.'})}",""
    ].join('\n');
    html=replaceBetween(html,"  async function saveDraft(notes=''){","  async function freshAllowedMap(){",account42,'V42_ACCOUNT');

    const submit42=[
      "  async function submitOrder(notes='',company=''){",
      "    const cleanNotes=String(notes||'').trim();if(!cartItems.length){setToast({type:'error',message:'السلة فارغة.'});return}if(EMPLOYEE_CUSTOMER_VIEW){setToast({type:'info',message:employeeViewNotice});return}setSubmitBusy(true);setValidationErrors([]);",
      "    try{let orderProfile=safeProfile,orderUid=String(user?.uid||'');if(guestMode){orderProfile=await ensureQuickCustomer(company);orderUid=orderProfile.uid}const allowed=await freshAllowedMap(),errors=cartItems.map(i=>({cleanId:i.cleanId,id:i.id,requested:i.totalQty,allowed:allowed.get(i.cleanId)||0})).filter(x=>x.requested>x.allowed+1e-9);if(errors.length){setValidationErrors(errors);setToast({type:'error',message:'تغير المتاح لبعض الأصناف. عدّل الكمية ثم أعد الاعتماد.'});return}const ref=db.collection(ORDER_COLLECTION).doc(),orderNo='BT-'+ref.id.slice(0,7).toUpperCase(),orderItems=cartItems.map(i=>({cleanId:i.cleanId,id:i.id,name:i.name,cartonPrice:Number(i.cartonPrice)||0,pack:i.pack||'',branchQuantities:i.branchQuantities,totalQty:i.totalQty})),orderCore={customerUid:orderUid,orderNo,customer:{name:orderProfile.name||currentGuestName(),company:orderProfile.company||String(company||'').trim(),phone:''},branches:branches.map(b=>({id:b.id,name:b.name})),items:orderItems,notes:cleanNotes,totalCartons,estimatedTotal:sum(cartItems.map(i=>(Number(i.cartonPrice)||0)*Number(i.totalQty||0))),status:'submitted',accountType:guestMode?'passwordless_device':'legacy_account'};await ref.set({...orderCore,createdAt:firebase.firestore.FieldValue.serverTimestamp(),checkoutVersion:6});const receipt={id:ref.id,...orderCore,createdAtLocal:Date.now()};try{sessionStorage.setItem(LAST_SUBMITTED_ORDER_KEY,JSON.stringify(receipt))}catch{}setSubmittedOrder(receipt);clearCustomerPendingAction();setCart({});setCheckout(false);await db.collection(CUSTOMER_COLLECTION).doc(orderUid).set({lastOrderNo:orderNo,lastOrderId:ref.id,lastOrderAt:firebase.firestore.FieldValue.serverTimestamp(),orderCount:firebase.firestore.FieldValue.increment(1),lastActivityAt:firebase.firestore.FieldValue.serverTimestamp(),lastActivityType:'order_submitted'},{merge:true});",
      "    }catch(e){console.error(e);setToast({type:'error',message:e?.message==='COMPANY_REQUIRED'?'اكتب اسم الشركة أو المؤسسة للمتابعة.':'تعذر اعتماد الطلب. السلة لم تُحذف؛ حاول مرة أخرى.'})}finally{setSubmitBusy(false)}",
      "  }",""
    ].join('\n');
    html=replaceBetween(html,"  async function submitOrder(notes){","  async function shareOrderWhatsApp(order){",submit42,'V42_SUBMIT');

    const checkout42=[
      "function Checkout({items,branches,profile,onBack,onDraft,onSubmit,busy,validationErrors,guestMode=false,initialNotes=''}){",
      "  const saved=currentQuickCustomerProfile(),[company,setCompany]=useState(()=>String(profile?.company||saved?.company||'')),[notes,setNotes]=useState(initialNotes||''),total=sum(items.map(i=>i.totalQty)),estimatedTotal=sum(items.map(i=>(Number(i.cartonPrice)||0)*Number(i.totalQty||0))),companyOk=!guestMode||company.trim().length>=2;",
      "  return <div className=\"grid gap-4\"><button onClick={onBack} className=\"w-fit h-10 px-3 rounded-10 border border-border bg-white flex items-center gap-2 text-sm\"><Icon name=\"back\" className=\"w-4 h-4\"/>العودة للسلة</button><div className=\"bg-white border border-border rounded-16 p-4\"><div className=\"text-xs text-muted\">اعتماد سريع</div><b className=\"block mt-1\">{items.length} صنف · {NF.format(total)} كرتون</b>{estimatedTotal>0&&<div className=\"text-xs text-accent mt-1 ltr\">≈ {PRICE_NF.format(estimatedTotal)} ر.س</div>}</div>",
      "    {guestMode&&<div className=\"bg-white border border-border rounded-16 p-4\"><label className=\"text-sm font-bold\">اسم الشركة / المؤسسة</label><p className=\"text-[11px] text-secondary mt-1 mb-3\">هذه المعلومة الوحيدة المطلوبة. سيتم إنشاء حسابك وحفظه تلقائيًا على هذا الجهاز بدون كلمة مرور.</p><input value={company} onChange={e=>setCompany(e.target.value)} className=\"ui-input\" autoComplete=\"organization\" placeholder=\"اكتب اسم الشركة أو المؤسسة\"/></div>}",
      "    {validationErrors?.length>0&&<div className=\"bg-dangerSoft border border-danger/20 rounded-16 p-4 text-danger text-xs\">راجع الكميات؛ تغير المتاح لبعض الأصناف.</div>}",
      "    <details className=\"bg-white border border-border rounded-16 p-4\"><summary className=\"text-xs font-bold cursor-pointer\">ملاحظة <span className=\"text-muted font-normal\">(اختياري)</span></summary><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows=\"3\" className=\"w-full rounded-12 border border-border p-3 mt-3\" placeholder=\"أي تعليمات إضافية...\"/></details>",
      "    <button disabled={busy||!companyOk} onClick={()=>onSubmit(notes,company)} className=\"h-14 rounded-14 bg-primary text-white font-bold disabled:opacity-40 flex items-center justify-center gap-2\">{busy?<Spinner/>:<><Icon name=\"check\" className=\"w-5 h-5\"/>اعتماد وإرسال الطلب</>}</button></div>",
      "}","\n\n"
    ].join('\n');
    html=replaceBetween(html,"function Checkout({items,branches,profile,onBack,onDraft,onSubmit,busy,validationErrors,guestMode=false,initialNotes=''}){","function OrderSuccessScreen",checkout42,'V42_CHECKOUT');

    const navOld="const nav=[['home','home','الرئيسية'],['categories','grid','الأقسام'],['cart','cart','السلة'],['orders','file','طلباتي'],['account','user','حسابي']];";if(!html.includes(navOld))throw new Error('V42_NAV');html=html.replace(navOld,"const nav=guestMode?[['home','home','الرئيسية'],['categories','grid','الأقسام'],['cart','cart','السلة']]:[['home','home','الرئيسية'],['categories','grid','الأقسام'],['cart','cart','السلة'],['orders','file','طلباتي']];");
    const rootStart="  if(authState==='loading'||registering)return <div",rootEnd="function CustomerPortalBootstrap(){";
    const root42=["  if(authState==='loading'||registering)return <div className=\"min-h-[100dvh] ui-auth-bg flex flex-col items-center justify-center gap-4 px-4\"><Spinner/><div className=\"text-sm font-semibold text-secondary\">جاري تجهيز البوابة...</div></div>;","  if(authState==='ready'&&profile)return <CustomerApp user={auth.currentUser} profile={profile} onProfileUpdate={setProfile}/>;","  return <><CustomerApp user={null} profile={currentQuickCustomerProfile()} guestMode={true} onProfileUpdate={()=>{}} onRequireAuth={()=>{}}/>{globalError&&<div className=\"fixed top-4 left-1/2 -translate-x-1/2 z-[100] bg-danger text-white rounded-12 p-3\">{globalError}</div>}</>;","}","\n\n"].join('\n');html=replaceBetween(html,rootStart,rootEnd,root42,'V42_ROOT');
    html=html.replace('<script src=\"https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4.1633559619/face_mesh.js\"></script>','');
    if(!html.includes('QUICK_CUSTOMER_PROFILE_KEY')||!html.includes("accountType:'passwordless_device'")||!html.includes('هذه المعلومة الوحيدة المطلوبة')||!html.includes("const nav=guestMode?")||html.includes("onRequireAuth?.('submit')"))throw new Error('V42_OUTPUT_CHECK');
'''
if 'V42: no customer password' not in s:s=s.replace(marker,block+marker,1)
p.write_text(s)
print('V42_SIMPLE_PATCHED')
