name: Update Version

on:
  push:
    paths:
      - 'data/jeddah.tsv'
      - 'data/riyadh.tsv'

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update version.json
        run: |
          DATE=$(TZ=Asia/Riyadh date +"%Y-%m-%d %H:%M")
          echo "{\"lastUpdate\":\"$DATE\"}" > data/version.json

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/version.json

          git diff --cached --quiet || git commit -m "Auto update version.json"

          git push
